### PR TITLE
Web Task 1 Completed

### PR DESCRIPTION
**Pull request by Sudipta004**

### CODE REVIEW

**Comment by AnanyaM007** [comment]
provide the link in the description

**Comment by AnanyaM007** [comment]
First of all, Great job. Really impressive and your code is clean and modular. Your background gradient is quite sexy. 

Check the responsiveness of website from 800px and below 
Tip: use flex-direction: column in media query

You can try and if you face any issues contact us. We'll help you out

**Comment by Sudipta004** [comment]
Thank you for the feedback on my website.

The website I submitted is actually responsive for below 800px


Sudipta

**Comment by Princerey** [comment]
@Sudipta004 Good Job !!

**Pull request merged**
