### PR TITLE
git web task 1 completed

### PR DESCRIPTION
**Pull request by Ritika-31**

### CODE REVIEW

**Review by Princerey — CHANGES_REQUESTED** [review]
You haven't hosted your website properly you local ip won't work for others . Please follow the instructions and update your website link.

**Comment by Princerey** [comment]
@Ritika-31 Also please check your file location . You have uploaded it in wrong directory . Correct that too.

**Comment by Ritika-31** [comment]
I have made changes can you check it

**Comment by Ritika-31** [comment]
I have added the file in task submission folder .......have I done this time correctly

**Comment by Ritika-31** [comment]
@Princerey I have added file into task submission folder ..........have I done this time correctly?

**Comment by Princerey** [comment]
@Ritika-31 Please delete everything else except the files in task submission folder. And https://www.youtube.com/watch?v=OltY8JIaP-4&themeRefresh=1 follow this and host your website correctly

**Comment by Ritika-31** [comment]
@Princerey I did it according to it kindly check it

**Comment by Princerey** [comment]
@Ritika-31 where is your hosted website link ?

**Comment by Ritika-31** [comment]
@Princerey inside the web development folder link.txt

**Comment by Princerey** [comment]
@Ritika-31 that isn't the hosted link please check the youtube link provided above to host your website properly

**Comment by Ritika-31** [comment]
@Princerey kindly check it https://ritika-31.github.io/Induction-2023/

**Comment by Princerey** [comment]
@Ritika-31 Good ....But one last change is place all the files inside a folder of your name Task Submission/Ritika

**Comment by Ritika-31** [comment]
@Princerey I changed the link inside as it was wrong I pasted the website link there

**Review by Princerey — APPROVED** [review]

**Pull request merged**
