### PR TITLE
Completed Web Task 1

### PR DESCRIPTION
**Pull request by swastik-mishra25**
https://swastik-mishra25.github.io/Swastikweb5.github.io/

### CODE REVIEW

**Review by Princerey — CHANGES_REQUESTED** [review]
@swastik-mishra25 add txt file with your website link

**Comment by swastik-mishra25** [comment]
The code... of the website?

**Comment by Princerey** [comment]
yes

**Comment by swastik-mishra25** [comment]
OK bhaiya...

**Comment by swastik-mishra25** [comment]
Bhaiya has my task got approved?

**Comment by Princerey** [comment]
add the text file it will get approved after that

**Review by swastik-mishra25 — COMMENTED** [review]
added the txt file

**Review by Princerey — APPROVED** [review]

**Pull request merged**
