### PR TITLE
Web Development task 1 completed

### PR DESCRIPTION
**Pull request by CSE26-sairaj**
https://cse26-sairaj.github.io/

### CODE REVIEW

**Review by Princerey — APPROVED** [review]
Good Job !!

**Comment by CSE26-sairaj** [comment]
> Good Job !!

Thank you bhaiya🙏

**Comment by CSE26-sairaj** [comment]
Made the webpage more responsive.
https://cse26-sairaj.github.io/CSE26-sairaj.github.io-Portfolio/

**Comment by AnanyaM007** [comment]
nicely done

**Comment by CSE26-sairaj** [comment]
> nicely done

Thank you didi.

**Pull request merged**
