### PR TITLE
Git

### PR DESCRIPTION
**Pull request by Yash282003**
https://yash282003.github.io/Induction_webpage2/

### CODE REVIEW

**Comment by Yash282003** [comment]
web development task1 completed is the real one.

**Comment by AnanyaM007** [comment]
check the responsiveness

**Comment by Princerey** [comment]
image
your content is overflowing do check the responsiveness of your website. Make the necessary changes.

**Comment by Yash282003** [comment]
@AnanyaM007 made some changes please check.
https://yash282003.github.io/Task_webD/

**Comment by Princerey** [comment]
@Yash282003 Great work ! The website is now fully responsive

**Review by Princerey — APPROVED** [review]

**Pull request merged**
