### PR TITLE
git week 2 task 1 completed

### PR DESCRIPTION
**Pull request by RoyKami**
https://roykami.github.io/

### CODE REVIEW

**Comment by AnanyaM007** [comment]
Smartly done! Colour palette is attractive. Study responsiveness...so you don't have to leave those gaps in both ends next time

**Comment by RoyKami** [comment]
> Smartly done! Colour palette is attractive. Study responsiveness...so you don't have to leave those gaps in both ends next time

yes, didi I am looking into responsiveness; as a matter of fact, I had to remove one of the images planned because it didn't scale with mobile devices.

**Comment by AnanyaM007** [comment]
Apart from that its the best original piece till now. Well done

**Comment by RoyKami** [comment]
Thank you

**Pull request merged**
