### PR TITLE
Web Development Task 1 completed

### PR DESCRIPTION
**Pull request by rahulpandarn**

### CODE REVIEW

**Review by Princerey — CHANGES_REQUESTED** [review]
You have uploaded your files in wrong location . Please follow the instructions properly. And also you haven't hosted your website. Provide screenshots and link of your hosted website.

**Comment by Princerey** [comment]
@rahulpandarn Delete the folder you created earlier and also place your task 1 txt file inside OpenSource/Task1 folder

**Comment by Princerey** [comment]
@rahulpandarn Move your task 1 text file to right folder too

**Comment by AnanyaM007** [comment]
there are  some random text after the  header. remove them

**Pull request merged**
