### PR TITLE
ritpa2005.github.io

### PR DESCRIPTION
**Pull request by ritpa2005**
https://github.com/ritpa2005/RiteshKumarPanda.github.io

### CODE REVIEW

**Review by Princerey — CHANGES_REQUESTED** [review]
@ritpa2005 You haven't hosted your website properly follow the instructions correctly . You have just provided the link to your repo.

**Comment by ritpa2005** [comment]
WEBPAGE me koi problem hai kya?

**Comment by Princerey** [comment]
@ritpa2005 Tumhara site host nae hua hai . First of all this is the link to your website https://ritpa2005.github.io/RiteshKumarPanda.github.io/ . Try renaming your html file to index.html to solve this error.

**Comment by ritpa2005** [comment]
https://ritpa2005.github.io/
This is the link to my website.

**Comment by Princerey** [comment]
@ritpa2005 Great work but please don't delete anything just add your stuffs.

**Comment by ritpa2005** [comment]
Sorry, but this pr is not accepted yet

**Comment by Princerey** [comment]
@ritpa2005 You have deleted the readme file and sample file you don't have to delete anything just add your files . Please correct it and commit again .

**Comment by Princerey** [comment]
@ritpa2005  revert the deletion of readme.md

**Comment by ritpa2005** [comment]
I have made the required changes. Is it alright now?

**Review by Princerey — APPROVED** [review]

**Pull request merged**
