### PR TITLE
git task 2 completed

### PR DESCRIPTION
**Pull request by DEATHGOD126**

### CODE REVIEW

**Comment by preritjn** [comment]
You don't have to create new file for task 2 just do the changes in same task 1 folder and commit

**Comment by DEATHGOD126** [comment]
Mam i have rechecked and made the necessary changes please level my pull request to approved
Thank you

**Comment by preritjn** [comment]
You delete the readme file. 
Revert your last commit

**Comment by DEATHGOD126** [comment]
how to revert my last commit please bhaiya tell me

**Comment by SySagar** [comment]
Follow these steps:
- git st - (it should show branch clean if not the then make sure it is)
-  git log (you will get a sequence of commits the latest will be your last commit)
-  copy the SHA (it will be something like this ''FE4R6Q...." not exactly but something like this)
- hit this command (git revert sha_copied_one)
- then see the commit

**Review by SySagar — APPROVED** [review]

**Review by DEATHGOD126 — COMMENTED** [review]
Bhaiya i have revert the commit please check it

**Pull request merged**
