### PR TITLE
https://syedfaizanurrahman.github.io/

### PR DESCRIPTION
**Pull request by syedfaizanurrahman**
week 2 task 1 completed

### CODE REVIEW

**Comment by syedfaizanurrahman** [comment]
week 2 task 1 completed

**Review by Princerey — CHANGES_REQUESTED** [review]
@syedfaizanurrahman Add your files to the correct directory . And also include a text file with link of your website.

**Comment by syedfaizanurrahman** [comment]
completed the required chamges

**Review by Princerey — APPROVED** [review]
Good Job !!

**Pull request merged**
