### PR TITLE
webdev task1 completed

### PR DESCRIPTION
**Pull request by priyadarshini004**

### CODE REVIEW

**Comment by AnanyaM007** [comment]
check the responsiveness

**Review by priyadarshini004 — COMMENTED** [review]
https://priyadarshini004.github.io/web_dev/

**Comment by Princerey** [comment]
Good Job !!

**Comment by AnanyaM007** [comment]
align the images column wise for lesser screen sizes

**Comment by priyadarshini004** [comment]
https://priyadarshini004.github.io/webdev/

**Pull request merged**
