### PR TITLE
git task 2 completed

### PR DESCRIPTION
**Pull request by sohamdhal**

### CODE REVIEW

**Review by SySagar — CHANGES_REQUESTED** [review]
You have changed some other file. Only change your own file.

**Comment by sohamdhal** [comment]
> You have changed some other file. Only change your own file.

Ok sir

**Comment by sohamdhal** [comment]
Sir I have once again done the changes and then add , commit and push
done...
Please review it.

**Comment by SySagar** [comment]
There has been no change. Please Remove Priyanka_Sabat.txt from your commit.

**Comment by sohamdhal** [comment]
> There has been no change. Please Remove Priyanka_Sabat.txt from your commit.

Can you please help me how to remove a file from the commit...

**Comment by sohamdhal** [comment]
Sir please check the last commit....Is it Ok..?

**Review by SySagar — APPROVED** [review]

**Pull request merged**
