### PR TITLE
web task 1 completed

### PR DESCRIPTION
**Pull request by ank-ita-nayak**

### CODE REVIEW

**Review by Princerey — CHANGES_REQUESTED** [review]
@ank-ita-nayak You haven't hosted your website properly . The problem is with the name of your index file change it to index.html from index.html.html . It should fix the issue.

**Comment by ank-ita-nayak** [comment]
I have done the required changes please check it

**Comment by Princerey** [comment]
@ank-ita-nayak Upload your images to the GitHub repo too. The images are not loading on your website as of now.

**Comment by ank-ita-nayak** [comment]
I have again corrected ..... Please check it

**Comment by Princerey** [comment]
@ank-ita-nayak Please edit your html as well change the img src to just the filename rather than img/filename because you have the files directly in your repo

**Comment by ank-ita-nayak** [comment]
Thank u so much bhaiya hogaya.... I have done the changes as you mentioned...please check

**Comment by ank-ita-nayak** [comment]
Now the images are showing. Please check it

**Comment by Princerey** [comment]
@ank-ita-nayak Good Job ! But can you please check the responsiveness of your page the content are overflowing .

**Comment by ank-ita-nayak** [comment]
Bhaiya actually  i am trying but it is still overflowing

**Comment by AnanyaM007** [comment]
Try using display :flex then  flex-direction column in media query

**Comment by ank-ita-nayak** [comment]
I tried but not working ....

**Pull request closed without merging**
